import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { motion } from "framer-motion";
import { useRouter } from "next/router";
import InfoSection from "@/components/Landing/info/info-section";
import TrustedBySection from "@/components/Landing/logos/logos-section";
import MoreInfoSection from "@/components/Landing/more-info/more-info";
import HomeNavbar from "@/components/Landing/navbar/home-navbar";
import StatsSection from "@/components/Landing/stats/stats-section";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Orderly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="flex h-full flex-col  bg-slate-900">
          <HomeNavbar />
          <section className="flex grow flex-col gap-10 px-6">
            <p className="px-2 text-center text-4xl font-semibold text-white ">
              Great teamwork starts with a
              <span className=" text-yellow-500"> digital HQ</span>
            </p>
            <motion.button
              initial={{ scale: 1 }}
              whileHover={{ scale: 1.01 }}
              whileTap={{ scale: 0.99 }}
              className="w-full rounded bg-slate-200 py-4 text-lg font-semibold text-slate-900 transition-all duration-300 "
              onClick={() => router.push("/sign-up")}
            >
              Sign up today
            </motion.button>
            <div className="mb-10">
              <div className=" h-96 w-full rounded-lg bg-blue-400" />
            </div>
          </section>
        </div>
        <div className="bg-orange-50 pb-12 lg:pb-20">
          <TrustedBySection />
          <InfoSection />
        </div>
        <StatsSection />
        <section className="bg-slate-900 px-4 py-20">
          <p className="mb-10 text-center text-3xl font-bold text-white">
            Welcome to your new digital HQ
          </p>
          <div className="mx-auto flex max-w-3xl flex-col gap-4 xl:flex-row">
            <button className="rounded bg-slate-50 py-4  font-semibold text-slate-900 transition-all  duration-300 hover:rounded-none hover:shadow-[inset_0px_0px_0px_3px_rgba(15,23,42,.3)] xl:w-1/2">
              Get Orderly today
            </button>
            <button className="rounded border border-white bg-slate-900 py-4 font-semibold text-white transition-all duration-200 hover:shadow-[inset_0px_0px_0px_1px_rgba(255,255,255,255)] xl:w-1/2 ">
              Get Orderly today
            </button>
          </div>
        </section>
        <div className="mx-auto max-w-7xl">
          <MoreInfoSection />
          <footer className="mt-10 px-6">
            <hr />
            <div className="flex flex-col gap-10 py-8 md:flex-row">
              <Link href="#" className="text-sm font-bold">
                Status
              </Link>
              <Link href="#" className="text-sm font-bold">
                Privacy
              </Link>
              <Link href="#" className="text-sm font-bold">
                Terms
              </Link>
              <Link href="#" className="text-sm font-bold">
                Cookie Preferences
              </Link>
              <Link href="#" className="text-sm font-bold">
                Contact Us
              </Link>
            </div>
          </footer>
        </div>
      </main>
    </>
  );
};

export default Home;
